In [4]:
import pandas as pd
from pathlib import Path

import numpy as np 
import matplotlib.pyplot as plt 
from itertools import permutations
from time import time 

import gc 
from scipy.spatial.distance import pdist, squareform
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import KNeighborsRegressor
import os

for dirname, _ , filenames in os.walk('ml-25m/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

ml-25m/links.csv
ml-25m/tags.csv
ml-25m/genome-tags.csv
ml-25m/ratings.csv
ml-25m/README.txt
ml-25m/genome-scores.csv
ml-25m/movies.csv

In [5]:
tic = time()

dataset_path = Path('ml-25m')

movies = pd.read_csv(dataset_path/"movies.csv")

ratings = pd.read_csv(dataset_path/"ratings.csv")

tags = pd.read_csv(dataset_path/"tags.csv")

genome_tags = pd.read_csv(dataset_path/"genome-tags.csv")

genome_scores = pd.read_csv(dataset_path/"genome-scores.csv")

links = pd.read_csv(dataset_path/"links.csv") 

toc = time()
print(toc - tic)

12.278394222259521

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # allow multiple outputs in a cell
import warnings
warnings.filterwarnings("ignore")

movies : movieId, title, genres

ratings : userId, movieId, rating, timestamp

tags : userId, movieId, tag, timestamp

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  62423 non-null  int64
 1   title    62423 non-null  object
 2   genres   62423 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

In [8]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000095 entries, 0 to 25000094
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 762.9 MB

In [9]:
tags.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093360 entries, 0 to 1093359
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   userId     1093360 non-null  int64
 1   movieId    1093360 non-null  int64
 2   tag        1093344 non-null  object
 3   timestamp  1093360 non-null  int64
dtypes: int64(3), object(1)
memory usage: 33.4+ MB

In [10]:
rating_movies_df = pd.merge(rating,movie,how = 'left', on = 'movieId')

rating_movies_df.head()

NameError: name 'rating' is not defined

In [ ]:
movie_popularity = rating_movies_df['title'].value_counts()
movie_popularity

Forrest Gump (1994)                 81491
Shawshank Redemption, The (1994)    81482
Pulp Fiction (1994)                 79672
Silence of the Lambs, The (1991)    74127
Matrix, The (1999)                  72674
                                    ...
Night Into Morning (1951)               1
Flirting with Fate (1916)               1
Cheerful Wind (1981)                    1
The Cuckoo Clock (1938)                 1
Il pesce innamorato (1999)              1
Name: title, Length: 58958, dtype: int64

In [11]:
movie_popularity = movie_popularity[movie_popularity > 500].index

In [12]:
popular_movies_rankings = rating_movies_df[rating_movies_df["title"].isin(movie_popularity)]
popular_movies_rankings.head()

,userId,movieId,rating,timestamp,title,genres
0,1,296,5.0,1147880044,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
1,1,306,3.5,1147868817,Three Colors: Red (Trois couleurs: Rouge) (1994),Drama
2,1,307,5.0,1147868828,Three Colors: Blue (Trois couleurs: Bleu) (1993),Drama
3,1,665,5.0,1147878820,Underground (1995),Comedy|Drama|War
4,1,899,3.5,1147868510,Singin' in the Rain (1952),Comedy|Musical|Romance

In [13]:
popular_movies_average_rankings = popular_movies_rankings[["title", "rating"]].groupby('title').mean()
popular_movies_average_rankings.sort_values(by="rating", ascending=False).head(10)

                                               rating
title
Planet Earth II (2016)                       4.483096
Planet Earth (2006)                          4.464797
Shawshank Redemption, The (1994)             4.413576
Band of Brothers (2001)                      4.398599
Godfather, The (1972)                        4.324336
Blue Planet II (2017)                        4.289833
Usual Suspects, The (1995)                   4.284353
Godfather: Part II, The (1974)               4.261759
Over the Garden Wall (2013)                  4.258242
Seven Samurai (Shichinin no samurai) (1954)  4.254769

In [1]:
import torch

In [2]:
def tabular_preview(ratings, n=15):
    """Creates a cross-tabular view of users vs movies."""
    
    user_groups = ratings.groupby('userId')['rating'].count()
    top_users = user_groups.sort_values(ascending=False)[:15]

    movie_groups = ratings.groupby('movieId')['rating'].count()
    top_movies = movie_groups.sort_values(ascending=False)[:15]

    top = (
        ratings.
        join(top_users, rsuffix='_r', how='inner', on='userId').
        join(top_movies, rsuffix='_r', how='inner', on='movieId'))

    return pd.crosstab(top.userId, top.movieId, top.rating, aggfunc=np.sum)

In [11]:
tabular_preview(ratings, movies)

movieId,1,50,110,260,296,318,356,480,527,589,593,1196,2571,2959,4993
userId,,,,,,,,,,,,,,,
20055,5.0,4.5,4.0,5.0,5.0,4.5,4.5,4.0,5.0,5.0,5.0,5.0,5.0,4.0,4.5
29803,4.0,3.0,4.0,5.0,5.0,5.0,4.0,2.0,5.0,3.5,3.5,5.0,5.0,5.0,5.0
30879,2.5,2.5,2.5,3.5,3.0,1.0,1.0,2.0,NaN,3.0,3.0,3.5,2.5,1.5,1.0
33844,3.5,5.0,4.0,0.5,5.0,5.0,3.5,3.0,4.5,3.5,5.0,0.5,1.5,4.5,3.0
49403,5.0,5.0,3.5,5.0,5.0,5.0,2.0,3.0,5.0,4.0,2.0,5.0,5.0,4.0,5.0
61010,4.0,4.0,4.0,4.0,4.5,4.0,3.5,4.0,4.0,4.0,4.5,4.0,4.0,4.5,4.0
72315,4.0,4.0,3.5,4.0,4.5,4.5,3.5,4.0,4.5,4.0,4.0,4.0,4.0,3.5,4.0
75309,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78849,NaN,4.0,3.5,5.0,3.5,4.5,4.0,3.0,4.0,3.0,4.0,4.5,2.5,3.0,3.0
80974,4.0,4.5,5.0,4.0,4.5,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0
92046,5.0,5.0,1.0,5.0,5.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0
109731,3.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.5,2.5,4.0,2.0,4.0
110971,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
115102,4.0,4.0,4.0,3.0,5.0,5.0,2.0,2.5,3.5,5.0,4.0,5.0,4.0,1.0,NaN
137293,3.0,4.0,4.0,4.0,4.0,4.5,3.0,4.0,4.0,4.0,4.0,4.0,4.5,4.0,4.5

In [12]:
def create_dataset(ratings, top=None):
    if top is not None:
        ratings.groupby('userId')['rating'].count()
    
    unique_users = ratings.userId.unique()
    user_to_index = {old: new for new, old in enumerate(unique_users)}
    new_users = ratings.userId.map(user_to_index)
    
    unique_movies = ratings.movieId.unique()
    movie_to_index = {old: new for new, old in enumerate(unique_movies)}
    new_movies = ratings.movieId.map(movie_to_index)
    
    n_users = unique_users.shape[0]
    n_movies = unique_movies.shape[0]
    
    X = pd.DataFrame({'user_id': new_users, 'movie_id': new_movies})
    y = ratings['rating'].astype(np.float32)
    return (n_users, n_movies), (X, y), (user_to_index, movie_to_index)

In [13]:
(n, m), (X, y), _ = create_dataset(ratings)
print(f'Embeddings: {n} users, {m} movies')
print(f'Dataset shape: {X.shape}')
print(f'Target shape: {y.shape}')

Embeddings: 162541 users, 59047 movies
Dataset shape: (25000095, 2)
Target shape: (25000095,)

In [14]:
class ReviewsIterator:
    
    def __init__(self, X, y, batch_size=32, shuffle=True):
        X, y = np.asarray(X), np.asarray(y)
        
        if shuffle:
            index = np.random.permutation(X.shape[0])
            X, y = X[index], y[index]
            
        self.X = X
        self.y = y
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.n_batches = int(math.ceil(X.shape[0] // batch_size))
        self._current = 0
        
    def __iter__(self):
        return self
    
    def __next__(self):
        return self.next()
    
    def next(self):
        if self._current >= self.n_batches:
            raise StopIteration()
        k = self._current
        self._current += 1
        bs = self.batch_size
        return self.X[k*bs:(k + 1)*bs], self.y[k*bs:(k + 1)*bs]

In [15]:
def batches(X, y, bs=32, shuffle=True):
    for xb, yb in ReviewsIterator(X, y, bs, shuffle):
        xb = torch.LongTensor(xb)
        yb = torch.FloatTensor(yb)
        yield xb, yb.view(-1, 1)

In [16]:
for x_batch, y_batch in batches(X, y, bs=4):
    print(x_batch)
    print(y_batch)
    break

NameError: name 'math' is not defined

In [17]:
class EmbeddingNet(nn.Module):
    """
    Creates a dense network with embedding layers.
    
    Args:
    
        n_users:            
            Number of unique users in the dataset.

        n_movies: 
            Number of unique movies in the dataset.

        n_factors: 
            Number of columns in the embeddings matrix.

        embedding_dropout: 
            Dropout rate to apply right after embeddings layer.

        hidden:
            A single integer or a list of integers defining the number of 
            units in hidden layer(s).

        dropouts: 
            A single integer or a list of integers defining the dropout 
            layers rates applyied right after each of hidden layers.
            
    """
    def __init__(self, n_users, n_movies,
                 n_factors=50, embedding_dropout=0.02, 
                 hidden=10, dropouts=0.2):
        
        super().__init__()
        hidden = get_list(hidden)
        dropouts = get_list(dropouts)
        n_last = hidden[-1]
        
        def gen_layers(n_in):
            """
            A generator that yields a sequence of hidden layers and 
            their activations/dropouts.
            
            Note that the function captures `hidden` and `dropouts` 
            values from the outer scope.
            """
            nonlocal hidden, dropouts
            assert len(dropouts) <= len(hidden)
            
            for n_out, rate in zip_longest(hidden, dropouts):
                yield nn.Linear(n_in, n_out)
                yield nn.ReLU()
                if rate is not None and rate > 0.:
                    yield nn.Dropout(rate)
                n_in = n_out
            
        self.u = nn.Embedding(n_users, n_factors)
        self.m = nn.Embedding(n_movies, n_factors)
        self.drop = nn.Dropout(embedding_dropout)
        self.hidden = nn.Sequential(*list(gen_layers(n_factors * 2)))
        self.fc = nn.Linear(n_last, 1)
        self._init()
        
    def forward(self, users, movies, minmax=None):
        features = torch.cat([self.u(users), self.m(movies)], dim=1)
        x = self.drop(features)
        x = self.hidden(x)
        out = torch.sigmoid(self.fc(x))
        if minmax is not None:
            min_rating, max_rating = minmax
            out = out*(max_rating - min_rating + 1) + min_rating - 0.5
        return out
    
    def _init(self):
        """
        Setup embeddings and hidden layers with reasonable initial values.
        """
        
        def init(m):
            if type(m) == nn.Linear:
                torch.nn.init.xavier_uniform_(m.weight)
                m.bias.data.fill_(0.01)
                
        self.u.weight.data.uniform_(-0.05, 0.05)
        self.m.weight.data.uniform_(-0.05, 0.05)
        self.hidden.apply(init)
        init(self.fc)
    
    
def get_list(n):
    if isinstance(n, (int, float)):
        return [n]
    elif hasattr(n, '__iter__'):
        return list(n)
    raise TypeError('layers configuraiton should be a single number or a list of numbers')

NameError: name 'nn' is not defined